### ISSUE TITLE
Transfer learning in practice: Size mismatch error

### ISSUE THREAD

**Issue by bchiem42** [mttga/pymarl_transformers#1]
Hi! 

Thanks a lot for this very interesting line of work. I am particularly curious about the zero-shot transfer learning performance shown in your paper. 
However, I don't understand how to "apply the networks trained in a particular task to the others" (as described in the paper) when the number of agents varies between tasks. 
For instance, I tried to naïvely load the checkpoint of a trained model on the "3m" SMAC map to apply it to the "8m" one, but as I expected I got a size mismatch error in the loading of the torch weights and biases: 

`RuntimeError: Error(s) in loading state_dict for TransformerAgent:
	size mismatch for q_basic.weight: copying a param with shape torch.Size([9, 32]) from checkpoint, the shape in current model is torch.Size([14, 32]).
	size mismatch for q_basic.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([14]).
`

Could you help me with this problem ? 
Many thanks for considering my request.

**Comment by hj5717** [comment]
Have you solved it?

**Comment by mttga** [comment]
This is very likely due to the fact that you're using the incorrect configuration file. Please use:

```
python3 src/main.py --config=transf_qmix_smac --env-config=sc2
```

a specific model has being desinged for Smac which uses the correct dimensins for action decoupling and you need to ensure you're using that one:

https://github.com/mttga/pymarl_transformers/blob/main/src/modules/agents/n_transf_agent_smac.py

**Comment by hj5717** [comment]
> 这很可能是由于您使用了不正确的配置文件。请使用：
> 
> ```
> python3 src/main.py --config=transf_qmix_smac --env-config=sc2
> ```
> 
> 已经为 Smac 设计了一个特定的模型，该模型使用正确的 dimensins 进行动作解耦，您需要确保使用该模型：
> 
> https://github.com/mttga/pymarl_transformers/blob/main/src/modules/agents/n_transf_agent_smac.py

So I'd like to ask if there is a need for a special design to show the effects of transfer learning in our own environment, or is it just a matter of saving the model, re-downloading the model, and changing the environmental parameters?

**Comment by mttga** [comment]
depending on the environment you just need to make sure that when you're changing env params the observation is still a matrix of vertices-tokens where the number of vertices-tokens can change but the feature dimension is preserved and that the number of actions is also the same. If it's not the same you can do action decoupling as per smac

**Comment by hj5717** [comment]
> 根据环境的不同，您只需要确保在更改 env 参数时，观察结果仍然是顶点标记的矩阵，其中顶点标记的数量可以更改，但保留特征维度，并且操作数也相同。如果不相同，您可以根据 smac 进行操作解耦

Thanks! Another thing that interests me is that in previous papers, introducing attention mechanisms into the Madrl algorithm can solve the problem of dimension explosion. Has the algorithm in the article considered this effect? Just started, the questions asked are quite basic, please forgive me.
