### ISSUE TITLE
Questions about Graph Observations

### ISSUE THREAD

**Issue by hj5717** [mttga/pymarl_transformers#2]
Hello teacher, I successfully TransformerQMix combined with my own environment and achieved very good results. But I have a question, in my environment, Graph based Observations require agent to get global information, is this not in line with CTDE training architecture? Also the observation dimension grows linearly with the number of intelligences making it difficult to train.

**Comment by mttga** [comment]
hi, the scale of dimensionality in respect to the number of agents is a general marl problem, but in the case of transfqmix the only thing that increases is the batch size (not the number of parameter). 

If you need to get global information you might start to think about communicating information between agents.

**Comment by hj5717** [comment]
> hi, the scale of dimensionality in respect to the number of agents is a general marl problem, but in the case of transfqmix the only thing that increases is the batch size (not the number of parameter).
> 
> If you need to get global information you might start to think about communicating information between agents.

Yes, the size of the MIX network and agent network does not increase. In my environment, all entities are agents. So I set the size of each agent's observations to be the characteristics of all agents * the number of agents (I don't know if this is correct), which makes the algorithm difficult to train as the number of agents increases.

**Comment by hj5717** [comment]
Hello, I ran smac's 27m vs 30m, and then my computer crashed directly. I would like to ask if it is possible to complete training in 2M time steps for scenarios like this on a very large scale? Do you have any techniques?

**Comment by mttga** [comment]
what's your hardware?

**Comment by hj5717** [comment]
> 你的硬件是什么？

I use the i7-12500 CPU for training, and the hardware has a running memory of 32GB

**Comment by hj5717** [comment]
> 你的硬件是什么？

I have tried to scale up training, but the model training takes a long time. I have reviewed the experimental results of SMAC in the paper and found that they were all completed in 2M time step. Can you explain in detail how to optimize this aspect?

**Comment by mttga** [comment]
You need a gpu

**Comment by hj5717** [comment]
> 所有者

Can you tell me the configuration of your experiment? Due to the large state space, does using a GPU require a significant amount of graphics memory?

**Comment by mttga** [comment]
For these kind of experiments you need _at least_ 10gb of gpu ram. But better from 20 above

**Comment by hj5717** [comment]
> 对于此类实验，_您至少_需要 10gb 的 gpu 内存。但从上面的 20 个开始更好

Thank you for your patient reply. Does the code need to be set to use CPU or GPU for training? The 32 running memory of the CPU is still insufficient. On the other hand, I have seen related posts stating that switching the training data of MADRL between GPU and memory will result in longer processing times.
