### ISSUE TITLE
Queries about the migratory nature of the algorithm

### ISSUE THREAD

**Issue by hj5717** [mttga/pymarl_transformers#3]
Hi, the code in the article adds Transformer and implements mobility in both Agent Network as well as Mix'ing Network. I have an idea to use only Transfor-mix network and still use rnn_agent for Agent Network. set each agent to observe only its own information and not use graph structure observation. Will this achieve mobility? I still use the graph structure's state, which contains information about all vertices.
I hope to get your answer if you have time, thank you very much!

**Comment by mttga** [comment]
please don't open repository issues for questions that are not relative to the repository.
